### ISSUE TITLE
مشکل با اندروید 6

### ISSUE THREAD

**Issue by maysamrasoli** [TurKurT656/HamrahPay#3]
سلام دوست عزیز

هنگام پرداخت در گوشی های با اندروید 6 , خطای زیر پیش میاد

`06-29 01:26:04.045 29841-30197/ir.bizcatalog.biz E/Volley: [505] NetworkDispatcher.run: Unhandled exception java.lang.SecurityException: getDeviceId: Neither user 10059 nor current process has android.permission.READ_PHONE_STATE.
                                                           java.lang.SecurityException: getDeviceId: Neither user 10059 nor current process has android.permission.READ_PHONE_STATE.
                                                               at android.os.Parcel.readException(Parcel.java:1599)
                                                               at android.os.Parcel.readException(Parcel.java:1552)
                                                               at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:4175)
                                                               at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:706)
                                                               at ir.devage.hamrahpay.HamrahPay.getDeviceID(HamrahPay.java:372)
                                                               at ir.devage.hamrahpay.HamrahPay.access$800(HamrahPay.java:59)
                                                               at ir.devage.hamrahpay.HamrahPay$3.getParams(HamrahPay.java:285)
                                                               at com.android.volley.Request.getBody(Request.java:468)
                                                               at com.android.volley.toolbox.HurlStack.addBodyIfExists(HurlStack.java:253)
                                                               at com.android.volley.toolbox.HurlStack.setConnectionParametersForRequest(HurlStack.java:227)
                                                               at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:107)
                                                               at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:97)
                                                               at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)`

ممنون میشم راهنمایی بفرمایید.

**Comment by TurKurT656** [comment]
علت مشکل اینه که شما اجازه دسترسی برای خواندن اطلاعات موبایل رو به برنامه ندادین. یادتون باشه در آندروید ۶ به بعد حتما این درخواست ها رو از کاربر بخواین
